# This is a basic workflow to help you get started with Actions

name: auto_CI

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependency
        run: |
             sudo apt update
             sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
             echo 'dependency installed'
      - name: Clone source code
        run: |
             git clone --depth=1 https://e.coding.net/hanwckf/rt-n56u/padavan.git /opt/rt-n56u
      - name: Build_toolchain
        run: |
             cd /opt/rt-n56u/toolchain-mipsel
             sh dl_toolchain.sh
      - name: Making
        run: |
             cd /opt/rt-n56u/trunk
             sudo fakeroot ./build_firmware_modify K2P_nano
             ./clear_tree
             sudo fakeroot ./build_firmware_modify K2P_nano
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
         name: Images
         path: /opt/rt-n56u/trunk/images
